version: '3'

services:
  # Proxies requests to internal/external services
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy-example
    depends_on:
        - frontend-report
        - api-service
        - ibm-service
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8008:80"

  # generates frontend reports
  frontend-report:
    image: frontend-report
    container_name: frontend-report
    build:
      context: ./frontend_report
    depends_on:
        - api-service
        - ibm-service
    ports:
      - "8009:80"
    restart: on-failure


  # Generates a random IBM value from Feb. 5 2020 min/max
  ibm-service:
    image: ibm-service
    container_name: ibm-service
    build:
      context: ./ibm_service
    ports:
      - "5001:5001"
    restart: on-failure

  # Retrieves the weather (or any other) api key(s)
  api-service:
    image: api-service
    container_name: api-service
    build:
      context: ./api_service
    ports:
      - "5002:5002"
    restart: on-failure